/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active menu items, ordered by category then name. */
        get: operations["listProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All orders, newest first. Admin only. */
        get: operations["listOrders"];
        put?: never;
        /**
         * Submit an order request. Not a checkout — no payment is taken
         *     here (see docs/adr/0002-order-fulfillment-model.md). Prices are
         *     looked up server-side from `productId`s; the client-supplied
         *     price, if any, is ignored.
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A single order, by id. Public — the order id itself (a uuid) is
         *     the access control, same as the confirmation-page link a
         *     customer gets after ordering. No customer accounts exist to
         *     authenticate against.
         */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change an order's status. Admin only. */
        patch: operations["updateOrderStatus"];
        trace?: never;
    };
    "/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange the shared admin password for a bearer token. This
         *     service issues the token but never sets a cookie — it has no
         *     concept of a browser, only of a bearer token. `web/` is the one
         *     that turns this token into an httpOnly cookie (see
         *     web/src/app/api/admin/login/route.ts).
         */
        post: operations["adminLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            errors: string[];
        };
        /** @enum {string} */
        FulfillmentMethod: "PICKUP" | "LOCAL_DELIVERY" | "IN_STATE_SHIPPING";
        /** @enum {string} */
        OrderStatus: "PENDING" | "CONFIRMED" | "READY" | "COMPLETED" | "CANCELLED";
        Product: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            description: string;
            /** @description Always integer cents — see specs/ENGINEERING_RULES.md "Money." */
            priceCents: number;
            category: string;
            imageUrl: string | null;
            allergens: string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        OrderItemWithProduct: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderId: string;
            /** Format: uuid */
            productId: string;
            quantity: number;
            /** @description Snapshot of the product's price at order time — not a live reference. See supabase/migrations/0001_init.sql. */
            unitPriceCents: number;
            product: components["schemas"]["Product"];
        };
        Order: {
            /** Format: uuid */
            id: string;
            customerName: string;
            customerEmail: string;
            customerPhone: string;
            fulfillmentMethod: components["schemas"]["FulfillmentMethod"];
            fulfillmentAddress: string | null;
            /**
             * @description A bare "YYYY-MM-DD" date-only string, not a timestamp — see
             *     specs/ENGINEERING_RULES.md "Date-only values." Never parse
             *     this with `new Date(str)` on either side of the boundary.
             */
            requestedDate: string;
            notes: string | null;
            status: components["schemas"]["OrderStatus"];
            subtotalCents: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        OrderWithItems: components["schemas"]["Order"] & {
            items: components["schemas"]["OrderItemWithProduct"][];
        };
        CreateOrderRequest: {
            customerName: string;
            customerEmail: string;
            customerPhone: string;
            fulfillmentMethod: components["schemas"]["FulfillmentMethod"];
            fulfillmentAddress?: string;
            /** @description YYYY-MM-DD — see Order.requestedDate. */
            requestedDate: string;
            notes?: string;
            items: {
                /** Format: uuid */
                productId: string;
                quantity: number;
            }[];
        };
    };
    responses: {
        /**
         * @description This API's one error envelope shape, used for every non-2xx
         *     response — see specs/ENGINEERING_RULES.md "Error envelope."
         *     Never `{ "error": "..." }` (singular) — that inconsistency
         *     existed in the pre-split codebase and was deliberately fixed
         *     when this spec was written, not carried forward.
         */
        Errors: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        OrderId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                    };
                };
            };
        };
    };
    listProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        products: components["schemas"]["Product"][];
                    };
                };
            };
        };
    };
    listOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        orders: components["schemas"]["OrderWithItems"][];
                    };
                };
            };
            401: components["responses"]["Errors"];
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Order created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        order: components["schemas"]["OrderWithItems"];
                    };
                };
            };
            400: components["responses"]["Errors"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        order: components["schemas"]["OrderWithItems"];
                    };
                };
            };
            404: components["responses"]["Errors"];
        };
    };
    updateOrderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    status: components["schemas"]["OrderStatus"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        order: components["schemas"]["Order"];
                    };
                };
            };
            400: components["responses"]["Errors"];
            401: components["responses"]["Errors"];
            404: components["responses"]["Errors"];
        };
    };
    adminLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
            401: components["responses"]["Errors"];
        };
    };
}
