/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Non-secret runtime config `web/` needs but doesn't hold itself —
         *     currently just PayPal's Client ID (see
         *     docs/adr/0006-online-payment-paypal.md for why it lives here
         *     instead of being duplicated into web/'s own env).
         */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active menu items, ordered by category then name. */
        get: operations["listProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All orders, newest first. Admin only. */
        get: operations["listOrders"];
        put?: never;
        /**
         * Submit an order request. Prices are looked up server-side from
         *     `productId`s; the client-supplied price, if any, is ignored. An
         *     order exists in `PENDING` / `UNPAID` regardless of
         *     `paymentMethod` — for a `PAYPAL` order, payment happens in a
         *     separate step after this call (see `POST /orders/{id}/paypal-order`
         *     and `POST /orders/{id}/capture-payment`), not as part of creating
         *     the order. See docs/adr/0002-order-fulfillment-model.md and
         *     docs/adr/0006-online-payment-paypal.md.
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A single order, by id. Public — the order id itself (a uuid) is
         *     the access control, same as the confirmation-page link a
         *     customer gets after ordering. No customer accounts exist to
         *     authenticate against.
         */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change an order's status. Admin only. */
        patch: operations["updateOrderStatus"];
        trace?: never;
    };
    "/orders/{id}/paypal-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Starts a PayPal Checkout for an existing order — creates a
         *     PayPal order sized to this order's own `subtotalCents` (never a
         *     client-supplied amount) and returns PayPal's order id for the
         *     PayPal JS SDK to use client-side. See
         *     docs/adr/0006-online-payment-paypal.md.
         */
        post: operations["createPayPalOrderForOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/capture-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Captures a buyer-approved PayPal payment for this order,
         *     server-side — never trusts a client-reported "payment succeeded."
         *     On success, the order's `paymentStatus` becomes `PAID` and its
         *     `status` becomes `CONFIRMED`. Idempotent: calling this again for
         *     an order that's already `PAID` returns the same success response
         *     rather than erroring. See docs/adr/0006-online-payment-paypal.md.
         */
        post: operations["capturePaymentForOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange the shared admin password for a bearer token. This
         *     service issues the token but never sets a cookie — it has no
         *     concept of a browser, only of a bearer token. `web/` is the one
         *     that turns this token into an httpOnly cookie (see
         *     web/src/app/api/admin/login/route.ts).
         */
        post: operations["adminLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            errors: string[];
        };
        /** @enum {string} */
        FulfillmentMethod: "PICKUP" | "LOCAL_DELIVERY" | "IN_STATE_SHIPPING";
        /** @enum {string} */
        OrderStatus: "PENDING" | "CONFIRMED" | "READY" | "COMPLETED" | "CANCELLED";
        /**
         * @description MANUAL = cash/Venmo/Zelle, settled directly with the baker at
         *     pickup/delivery (the original, and still-default, model). PAYPAL
         *     = paid online through PayPal Checkout. See
         *     docs/adr/0006-online-payment-paypal.md.
         * @enum {string}
         */
        PaymentMethod: "MANUAL" | "PAYPAL";
        /** @enum {string} */
        PaymentStatus: "UNPAID" | "PAID";
        Product: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            description: string;
            /** @description Always integer cents — see specs/ENGINEERING_RULES.md "Money." */
            priceCents: number;
            category: string;
            imageUrl: string | null;
            allergens: string;
            /** @description Full ingredients statement, as required on a California cottage food product label. */
            ingredients: string;
            /** @description Net weight as printed on the label, e.g. "8 oz (226 g)" — a formatted display string, not a numeric quantity to compute with. */
            netWeight: string;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        OrderItemWithProduct: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderId: string;
            /** Format: uuid */
            productId: string;
            quantity: number;
            /** @description Snapshot of the product's price at order time — not a live reference. See supabase/migrations/0001_init.sql. */
            unitPriceCents: number;
            product: components["schemas"]["Product"];
        };
        Order: {
            /** Format: uuid */
            id: string;
            customerName: string;
            customerEmail: string;
            customerPhone: string;
            fulfillmentMethod: components["schemas"]["FulfillmentMethod"];
            fulfillmentAddress: string | null;
            /**
             * @description A bare "YYYY-MM-DD" date-only string, not a timestamp — see
             *     specs/ENGINEERING_RULES.md "Date-only values." Never parse
             *     this with `new Date(str)` on either side of the boundary.
             */
            requestedDate: string;
            notes: string | null;
            status: components["schemas"]["OrderStatus"];
            subtotalCents: number;
            paymentMethod: components["schemas"]["PaymentMethod"];
            paymentStatus: components["schemas"]["PaymentStatus"];
            /** @description Set once a PayPal Checkout has been started for this order (see POST /orders/{id}/paypal-order). Null for a MANUAL order, or a PAYPAL order for which checkout hasn't started yet. */
            paypalOrderId: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        OrderWithItems: components["schemas"]["Order"] & {
            items: components["schemas"]["OrderItemWithProduct"][];
        };
        CreateOrderRequest: {
            customerName: string;
            customerEmail: string;
            customerPhone: string;
            fulfillmentMethod: components["schemas"]["FulfillmentMethod"];
            fulfillmentAddress?: string;
            /** @description YYYY-MM-DD — see Order.requestedDate. */
            requestedDate: string;
            notes?: string;
            /** @description Omit for the default (MANUAL). */
            paymentMethod?: components["schemas"]["PaymentMethod"];
            items: {
                /** Format: uuid */
                productId: string;
                quantity: number;
            }[];
        };
    };
    responses: {
        /**
         * @description This API's one error envelope shape, used for every non-2xx
         *     response — see specs/ENGINEERING_RULES.md "Error envelope."
         *     Never `{ "error": "..." }` (singular) — that inconsistency
         *     existed in the pre-split codebase and was deliberately fixed
         *     when this spec was written, not carried forward.
         */
        Errors: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        OrderId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                    };
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Null if PAYPAL_CLIENT_ID isn't configured in this environment. */
                        paypalClientId: string | null;
                    };
                };
            };
        };
    };
    listProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        products: components["schemas"]["Product"][];
                    };
                };
            };
        };
    };
    listOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        orders: components["schemas"]["OrderWithItems"][];
                    };
                };
            };
            401: components["responses"]["Errors"];
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Order created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        order: components["schemas"]["OrderWithItems"];
                    };
                };
            };
            400: components["responses"]["Errors"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        order: components["schemas"]["OrderWithItems"];
                    };
                };
            };
            404: components["responses"]["Errors"];
        };
    };
    updateOrderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    status: components["schemas"]["OrderStatus"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        order: components["schemas"]["Order"];
                    };
                };
            };
            400: components["responses"]["Errors"];
            401: components["responses"]["Errors"];
            404: components["responses"]["Errors"];
        };
    };
    createPayPalOrderForOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        paypalOrderId: string;
                    };
                };
            };
            400: components["responses"]["Errors"];
            404: components["responses"]["Errors"];
        };
    };
    capturePaymentForOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    paypalOrderId: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        order: components["schemas"]["Order"];
                    };
                };
            };
            400: components["responses"]["Errors"];
            404: components["responses"]["Errors"];
        };
    };
    adminLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
            401: components["responses"]["Errors"];
        };
    };
}
